KITCAR_GAZEBO_SIM_PATH=$KITCAR_REPO_PATH/kitcar-gazebo-simulation/simulation

source /usr/share/gazebo-9/setup.sh

export GAZEBO_RESOURCE_PATH=$KITCAR_GAZEBO_SIM_PATH/models:$GAZEBO_RESOURCE_PATH
export GAZEBO_MODEL_PATH=$KITCAR_GAZEBO_SIM_PATH/models/env_db:$KITCAR_GAZEBO_SIM_PATH/models/model_db:$KITCAR_GAZEBO_SIM_PATH/models/tiles_db:$GAZEBO_MODEL_PATH

export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$KITCAR_GAZEBO_SIM_PATH/src
export PYTHONPATH=$PYTHONPATH:$KITCAR_GAZEBO_SIM_PATH/utils

export PYTHONPATH=$PYTHONPATH:$KITCAR_GAZEBO_SIM_PATH/simulation/src/simulation_brain_link/src
export PYTHONPATH=$PYTHONPATH:$KITCAR_GAZEBO_SIM_PATH/simulation/src/gazebo_simulation/src

source $KITCAR_GAZEBO_SIM_PATH/devel/setup.bash --extend
