KITCAR_GAZEBO_SIM_PATH=$KITCAR_REPO_PATH/kitcar-gazebo-simulation/simulation

export GAZEBO_RESOURCE_PATH=$KITCAR_GAZEBO_SIM_PATH/models:$GAZEBO_RESOURCE_PATH
export GAZEBO_MODEL_PATH=$KITCAR_GAZEBO_SIM_PATH/models/env_db:$GAZEBO_MODEL_PATH
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$KITCAR_GAZEBO_SIM_PATH/src
export PYTHONPATH=$PYTHONPATH:$KITCAR_REPO_PATH/kitcar-gazebo-simulation

source /usr/share/gazebo/setup.sh
source $KITCAR_GAZEBO_SIM_PATH/devel/setup.bash --extend
