echo 'exporting kitcar-gazebo-simulation path variables'

export KITCAR_GAZEBO_SIM_PATH=$KITCAR_REPO_PATH/kitcar-gazebo-simulation

export GAZEBO_RESOURCE_PATH=$KITCAR_GAZEBO_SIM_PATH/data:$GAZEBO_RESOURCE_PATH
export GAZEBO_MODEL_PATH=$KITCAR_GAZEBO_SIM_PATH/data/models/vehicles:$GAZEBO_MODEL_PATH
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$KITCAR_GAZEBO_SIM_PATH/src


