#!/usr/bin/env python3
import sys
import unittest
import os
import runpy

import rospkg
import rospy

rospack = rospkg.RosPack()

PKG = "gazebo_simulation"


class GenerateCarModelTest(unittest.TestCase):
    def test_car_generation(self):
        """Simply execute the generation script."""
        rospy.init_node("test_car_generation")
        generate_dr_drift = runpy.run_path(
            os.path.dirname(__file__) + "/../scripts/generate_dr_drift"
        )
        # Test generating dr drift from car specs files within kitcar-gazebo-simulation
        specs_path = os.path.join(
            rospack.get_path("gazebo_simulation"), "param", "car_specs", "dr_drift"
        )

        generate_dr_drift["generate"](base=specs_path, car_specs_base=specs_path)


if __name__ == "__main__":
    import rostest

    rostest.rosrun(PKG, "test_car_generation", GenerateCarModelTest, sys.argv)
