#! /usr/bin/env python3
from contextlib import suppress

import rospy

from simulation.src.simulation_brain_link.src.sensor_tof.node import SensorTofNode

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        SensorTofNode()
