#! /usr/bin/env python3
import rospy
from contextlib import suppress

from simulation.src.simulation_brain_link.src.vehicle_simulation_link.node import (
    VehicleSimulationLinkNode,
)

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        VehicleSimulationLinkNode()
