#! /usr/bin/env python3
import rospy
from contextlib import suppress

from simulation.src.gazebo_simulation.src.automatic_drive.node import AutomaticDriveNode

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        AutomaticDriveNode()
