#! /usr/bin/env python3
from contextlib import suppress

import rospy

from simulation.src.gazebo_simulation.src.car_state import CarStateNode

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        CarStateNode()
