#! /usr/bin/env python3
from contextlib import suppress

import rospy

from simulation.src.gazebo_simulation.src.gazebo_rate_control.node import (
    GazeboRateControlNode,
)

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        GazeboRateControlNode()
