image: ditschuk/docker-gazebo-build:latest

variables:
  CCACHE_DIR: "ccache"
  GIT_STRATEGY: clone
  PIP3_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ccache
    - .cache/pip
    - venv/

before_script: 
  - mkdir -p .pip
  - python3 -V               # Print out python version for debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt
  - mkdir -p ccache
    #Install python packages
  #- ls $KITCAR_REPO_PATH
  #- git lfs pull
  - export KITCAR_REPO_PATH=/builds/kitcar/
  - if [ -d "kitcar-ros" ]; then
  - mv kitcar-ros $KITCAR_REPO_PATH/kitcar-ros
  - fi
after_script:
  - export KITCAR_REPO_PATH=/builds/kitcar/
  - if [ -d "$KITCAR_REPO_PATH/kitcar-ros" ]; then
  - mv $KITCAR_REPO_PATH/kitcar-ros kitcar-ros
  - fi
  - ls $KITCAR_REPO_PATH

stages:
  - prebuild-test # Some tests are performed before building, to filter easy mistakes
  - build



# Test if dr_drift generation script works
test-dr_drift:
    stage: prebuild-test
    script: &prebuild-dr_drift
        - cd models/model_db/dr_drift
        - ./generate.sh
        #TODO: Also test if the calibration is actually correct.

test-road-generation:
  stage: prebuild-test
  script: &prebuild-generation
    - cd models/env_db
    - ./generate.sh -r default-road

build:
    stage: build
    script: &build-all
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.kitcar-team.de/kitcar/kitcar-ros.git $KITCAR_REPO_PATH/kitcar-ros
        - cd $KITCAR_REPO_PATH/kitcar-ros
        - git submodule sync --recursive
        - git submodule update --init --recursive
        - git clean -d -f -f KITcar_external/src
        #External
        - echo "CCACHE_DIR=$CCACHE_DIR"
        - cd $KITCAR_REPO_PATH/kitcar-ros/KITcar_external
        - catkin_make #-DCMAKE_BUILD_TYPE=Coverage
        - source $KITCAR_REPO_PATH/kitcar-ros/KITcar_external/devel/setup.bash --extend
        #Brain
        - cd $KITCAR_REPO_PATH/kitcar-ros/KITcar_brain
        - catkin_make  #-DCMAKE_BUILD_TYPE=Coverage
        - source $KITCAR_REPO_PATH/kitcar-ros/KITcar_brain/devel/setup.bash --extend
        - cd  $KITCAR_REPO_PATH/kitcar-ros/KITcar_debugger
        - catkin_make #-DCMAKE_BUILD_TYPE=Coverage
        - cd  $KITCAR_REPO_PATH/kitcar-gazebo-simulation
        - catkin_make
    artifacts:
        paths:
        - kitcar-ros
        - devel
        - build
        expire_in: 6 hrs
    

