# See https://pre-commit.com for more information
    # See https://pre-commit.com/hooks.html for more hooks
    default_language_version:
      python: python3.6
    repos:
      - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.0.0
        hooks:
          - id: flake8
