# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://medium.com/staqu-dev-logs/keeping-python-code-clean-with-pre-commit-hooks-black-flake8-and-isort-cac8b01e0ea1
default_language_version:
  python: python3.8
repos:
  # Hooks that modify code
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
  - id: seed-isort-config
- repo: https://github.com/PyCQA/isort
  rev: 5.7.0
  hooks:
  - id: isort
- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
  - id: docformatter
    args: [-i, --wrap-summaries, '92', --wrap-descriptions, '92']
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.1.0
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '92', --implicit_start, --preserve-quotes]

  # Hooks for validation
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-yaml
    args: ["--unsafe"]
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: check-ast
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
- repo: git://github.com/detailyang/pre-commit-shell
  rev: 1.0.5
  hooks:
  - id: shell-lint
- repo: https://github.com/asottile/pyupgrade
  rev: v2.10.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
