#! /usr/bin/env python3
from contextlib import suppress

import rospy

from simulation.src.simulation_groundtruth.src.groundtruth.visualization import (
    GroundtruthVisualizationNode,
)

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        GroundtruthVisualizationNode()
