#! /usr/bin/env python3
import rospy
from contextlib import suppress

from simulation.src.simulation_groundtruth.src.groundtruth.node import GroundtruthNode

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        GroundtruthNode()
