#! /usr/bin/env python3
import rospy
from contextlib import suppress

from groundtruth.test.mock_node import GroundtruthMockNode

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        GroundtruthMockNode()
