#! /usr/bin/env python3
import rospy
from contextlib import suppress

from groundtruth.node import GroundtruthNode

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        GroundtruthNode()
