display_env: main #visdom display environment name (default is "main")
display_freq: 5 #frequency of showing training results on screen
display_id: 1 #window id of the web display
display_port: 8097 #visdom port of the web display
display_server: http://localhost #visdom server of the web display
epoch_count: 1 #the starting epoch count, we save the model by <epoch_count>, <epoch_count>+<save_latest_freq>, ...
isTrain: True # enable or disable training mode
no_dropout: True #no dropout for the generator
no_html: False #do not save intermediate training results to [opt.checkpoints_dir]/[opt.name]/web/
num_threads: 8 # # threads for loading data
print_freq: 100 #frequency of showing training results on console
save_by_iter: False #whether saves model by iteration
save_epoch_freq: 1 #frequency of saving checkpoints at the end of epochs
save_latest_freq: 1000 #frequency of saving the latest results
update_html_freq: 100 #frequency of saving training results to html
