#! /usr/bin/env python3
#import update_sys_path

import rospy
from visualization.groundtruth import VisualizationNode


if __name__ == '__main__':
    # Initialize the node and name it.
    #rospy.init_node('simulation_groundtruth')
    # Go to class functions that do all the heavy lifting.
    try:
        VisualizationNode()
    except rospy.ROSInterruptException:
        pass
