#!/usr/bin/env python3
import sys
import rospy
import unittest

from simulation.utils.ros_base.node_base import NodeBase

PKG = "simulation_groundtruth"


class GroundtruthTestVisualizationNode(unittest.TestCase, NodeBase):
    """Unittest which tests the groundtruth visualization node.

    This test simply checks, that all visualization publishers exist and
    therefore validates, that the visualization node has not crashed.
    """

    def setUp(self):
        NodeBase.__init__(
            self, name="groundtruth_test_visualization", log_level=rospy.DEBUG
        )

    def test_publishers(self):
        """Perform some basic checks that ROS messages are sent."""

        # Wait for a message on all topics
        # WARNING: This requires to use a road that contains all elements!!!
        for topic in self.param.topics.visualization.as_dict().values():
            rospy.wait_for_message(topic, rospy.AnyMsg)


if __name__ == "__main__":
    import rostest

    rostest.rosrun(
        PKG,
        "test_groundtruth_visualization_node",
        GroundtruthTestVisualizationNode,
        sys.argv,
    )
