#! /usr/bin/env python3
import rospy
from contextlib import suppress

from car_state.visualization import CarStateVisualizationNode

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        CarStateVisualizationNode()
