#! /usr/bin/env python3
import rospy

from car_state.visualization import CarStateVisualizationNode

if __name__ == '__main__':
    try:
        CarStateVisualizationNode()
    except rospy.ROSInterruptException:
        pass
