#! /usr/bin/env python3
import rospy


from gazebo_timer.gazebo_timer_node import GazeboTimerNode

if __name__ == '__main__':
    # Initialize the node and name it.
    #rospy.init_node('simulation_groundtruth')
    # Go to class functions that do all the heavy lifting.
    try:
        GazeboTimerNode()
    except rospy.ROSInterruptException:
        pass
