#! /usr/bin/env python3
import rospy
from contextlib import suppress

from model_interface.node import ModelInterfaceNode

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        ModelInterfaceNode()
