#! /usr/bin/env python3
from contextlib import suppress

import rospy
from onboarding.node import OnboardingNode

if __name__ == "__main__":
    # Start the node
    with suppress(rospy.ROSInterruptException):
        OnboardingNode()
