# Topic frequency requirements
# If any of the topics are not publishing at all,
# they are not considered!
targets:
  - topic: /camera/image_raw
    desired: 55
  - topic: /simulation/speaker/broadcast
    desired: 25

# Restrictions on how much the gazebo update rate can be changed
# Prevent stopping the simulation
update_rate:
  min: 10
  max: 1500

  # Parameters for adjusting the gazebo update rate
  control:
    up: 0.01  # factor controlling the increase of the update rate
    down: 0.002  # factor controlling the decrease of the update rate
    rate: 30  # Rate with which the update_rate is changed
